name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create tarball of the code
      run: |
        tar -czf code.tar.gz .

    - name: Ensure destination directory exists
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "mkdir -p ~/qrcode/tbqrcode"

    - name: Copy tarball via SSH
      run: |
        scp -r code.tar.gz ubuntu@52.221.201.230:~/qrcode/tbqrcode

    - name: Extract tarball on the server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "tar -xzf ~/qrcode/tbqrcode/code.tar.gz -C ~/qrcode/tbqrcode"

    - name: Install dependencies and restart service
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 << 'EOF'
          source ~/qrcode/tbqrcode/venv/bin/activate
          cd ~/qrcode/tbqrcode
          pip install -r requirements.txt
          sudo systemctl restart qrapp
        EOF

    - name: Debug - Check service status
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "sudo systemctl status qrapp"
