name: Deploy to AWS

on:
  push:
    branches:
      - main  # Thay đổi branch này nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clean up old deployment
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "rm -rf ~/qrcode/tbqrcode/*"

    - name: Copy files via SSH
      run: |
        scp -r * ubuntu@52.221.201.230:~/qrcode/tbqrcode

    - name: Install dependencies and restart service
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 << 'EOF'
          source ~/qrcode/tbqrcode/venv/bin/activate
          cd ~/qrcode/tbqrcode
          pip install -r requirements.txt
          sudo systemctl restart qrapp
        EOF
