name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Ensure destination directory exists
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "mkdir -p ~/qrcode/tbqrcode"

    - name: Sync files via rsync
      run: |
        rsync -avz --delete . ubuntu@52.221.201.230:/home/ubuntu/qrcode/tbqrcode

    - name: Stop Gunicorn if running
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 << 'EOF'
          if pgrep -f gunicorn; then
            sudo systemctl stop qrapp
            pkill -f gunicorn
          fi
        EOF

    - name: Install dependencies and restart service
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 << 'EOF'
          source /home/ubuntu/qrcode/tbqrcode/venv/bin/activate
          cd /home/ubuntu/qrcode/tbqrcode
          pip install -r requirements.txt
          sudo systemctl daemon-reload
          sudo systemctl restart qrapp
        EOF

    - name: Debug - Check service status
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.221.201.230 "sudo systemctl status qrapp"
